### ISSUE TITLE
Not Running After Flathub Upgrade

### ISSUE THREAD

**Issue by feferd** [mijorus/gearlever#106]
here is a log

linuxmint cinnamon

flatpak run it.mijorus.gearlever
Logging to file /home/user/.var/app/it.mijorus.gearlever/cache/logs/gearlever.log
Traceback (most recent call last):
  File "/app/share/gearlever/gearlever/main.py", line 90, in do_activate
    self.win = GearleverWindow(application=self, from_file=from_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/GearleverWindow.py", line 75, in __init__
    self.installed_apps_list.refresh_list()
  File "/app/share/gearlever/gearlever/InstalledAppsList.py", line 106, in refresh_list
    list_row.load_icon()
  File "/app/share/gearlever/gearlever/components/AppListBoxItem.py", line 84, in load_icon
    image = appimage_provider.get_icon(self._app)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 179, in get_icon
    extracted = self._load_appimage_metadata(el)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 708, in _load_appimage_metadata
    mounted_appimage_path = self._extract_appimage(el)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 685, in _extract_appimage
    raise Exception('This file does not look like an AppImage, AppRun is missing')
Exception: This file does not look like an AppImage, AppRun is missing

**Comment by mijorus** [comment]
The whole app is not running, or there is a specific app image which is not running

**Comment by mijorus** [comment]
Hi, the latest version should include a bunch of bug fix that should fix this issue, please let me know if the issue was fixed for you

**Comment by feferd** [comment]
Now it works. 

Thank U, :1st_place_medal:

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
