### ISSUE TITLE
AppRun is Missing issue

### ISSUE THREAD

**Issue by dCo3lh0** [mijorus/gearlever#109]
Since i've updated to version 2.0, i lost all the registry of the appimage folder, so just for security sake since the icons could conflict with existing desktop files and entries in the application menu, so i've rollback to a week before version of flatpak, copied all existing appimages registered to a backup folder, removed all entries using the old gear lever 1.6.0 i think, updated gear lever to 2.0, and manually re-added all appimages again, but there is a problem, some appimages it freezes and refuse to "unlock" it, keeps on loading forever, so i can't add these ones, so I've run gear lever in terminal, and it presented me some errors in the log so I am sharing here

Here is the logs:

> flatpak run it.mijorus.gearlever
Logging to file /home/dco3lh0/.var/app/it.mijorus.gearlever/cache/logs/gearlever.log
Exception in thread Thread-1 (fetch_updates):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/gearlever/gearlever/InstalledAppsList.py", line 149, in fetch_updates
    app_conf = read_config_for_app(row._app)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/lib/json_config.py", line 33, in read_config_for_app
    b64name = base64.b64encode(el.name.encode('ascii')).decode('ascii')
                               ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xea' in position 4: ordinal not in range(128)
Exception in thread Thread-3 (load):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/gearlever/gearlever/AppDetails.py", line 258, in load
    icon = self.provider.get_icon(self.app_list_element)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 179, in get_icon
    extracted = self._load_appimage_metadata(el)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 708, in _load_appimage_metadata
    mounted_appimage_path = self._extract_appimage(el)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 685, in _extract_appimage
    raise Exception('This file does not look like an AppImage, AppRun is missing')
Exception: This file does not look like an AppImage, AppRun is missing
Exception in thread Thread-4 (fetch_updates):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/gearlever/gearlever/InstalledAppsList.py", line 149, in fetch_updates
    app_conf = read_config_for_app(row._app)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/lib/json_config.py", line 33, in read_config_for_app
    b64name = base64.b64encode(el.name.encode('ascii')).decode('ascii')
                               ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xea' in position 4: ordinal not in range(128)
Exception in thread Thread-6 (load):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/gearlever/gearlever/AppDetails.py", line 258, in load
    icon = self.provider.get_icon(self.app_list_element)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 179, in get_icon
    extracted = self._load_appimage_metadata(el)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 708, in _load_appimage_metadata
    mounted_appimage_path = self._extract_appimage(el)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 685, in _extract_appimage
    raise Exception('This file does not look like an AppImage, AppRun is missing')
Exception: This file does not look like an AppImage, AppRun is missing
Exception in thread Thread-7 (fetch_updates):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/gearlever/gearlever/InstalledAppsList.py", line 149, in fetch_updates
    app_conf = read_config_for_app(row._app)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/lib/json_config.py", line 33, in read_config_for_app
    b64name = base64.b64encode(el.name.encode('ascii')).decode('ascii')
                               ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xea' in position 4: ordinal not in range(128)

**Comment by mijorus** [comment]
Can you please tell me the app you are trying to install?

**Comment by mijorus** [comment]
Hi, the latest version should include a bunch of bug fix that should fix this issue, please let me know if the issue was fixed for you

**Comment by dCo3lh0** [comment]
instantly solved, thanks!

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
