### ISSUE TITLE
Appimage unable to run or install after unlock.

### ISSUE THREAD

**Issue by DIGist** [mijorus/gearlever#213]
Loading an appimage seems fine:
![image](https://github.com/user-attachments/assets/282db622-d25b-4ddd-8aba-1b2a89e5d3ed)

After hitting unlock though, it blanks the info and launch/move to app menu remain inactive:
![image](https://github.com/user-attachments/assets/43fc0c65-6333-4397-b1fe-fa7eb415c60d)

Log shows:
---- Application startup | version 2.3.2
2024-12-25 02:54:53,879 INFO [AppImageProvider.py:675] Exctracting with p7zip to /tmp/it.mijorus.gearlever/appimages/gearlever_5588xcdrb4/squashfs-root
2024-12-25 19:49:34,542 INFO [main.py:63]

Tried giving the gear level access to /tmp and running.. Get a new error:
ERROR: /home/user/AppImages/Cromite-v131.0.6778.205-anylinux-x86_64.AppImage
Can not open the file as archive

Exception in thread Thread-2 (load):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/gearlever/gearlever/AppDetails.py", line 258, in load
    icon = self.provider.get_icon(self.app_list_element)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 179, in get_icon
    extracted = self._load_appimage_metadata(el)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 702, in _load_appimage_metadata
    mounted_appimage_path = self._extract_appimage(el)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 677, in _extract_appimage
    z7zoutput = '\n\n' + terminal.sandbox_sh(['7z', 'x', file.get_path(), f'-o{squashfs_root_folder}', '-y', '-bso0', 'bsp0', 
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/lib/terminal.py", line 52, in sandbox_sh
    raise e
  File "/app/share/gearlever/gearlever/lib/terminal.py", line 44, in sandbox_sh
    output.check_returncode()
  File "/usr/lib/python3.12/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['7z', 'x', '/home/user/AppImages/Cromite-v131.0.6778.205-anylinux-x86_64.AppImage', '-o/tmp/it.mijorus.gearlever/appimages/gearlever_r8racx3817/squashfs-root', '-y', '-bso0', 'bsp0', '*.png', '*.svg', '*.desktop', '.DirIcon', '-r']' returned non-zero exit status 2.

Appimage  is: https://github.com/pkgforge-dev/Cromite-AppImage/releases

**Comment by hotlittlewhitedog** [comment]
I experienced the same problem when I took an appimage not in the folder used by GearLever. It was a problem of permissions in the log. If you move the appimage to the folder set in the preferences, it works.

**Comment by DIGist** [comment]
Thanks for the share, Unfortunately it seems to still result in the same behavior.

**Comment by hotlittlewhitedog** [comment]
I created the folder for Gear, in Gear when selecting the preferred folder (it will open a file manager).

**Comment by hotlittlewhitedog** [comment]
I got this err. 
Here I selected the Appimage in another folder (/appImagesClassic) and try to run it without moving.  

```
2024-12-28 16:00:07,713 DEBUG [AppImageProvider.py:664] Created temporary folder at /tmp/it.mijorus.gearlever/appimages/gearlever_2r546da67p
2024-12-28 16:00:07,713 INFO [AppImageProvider.py:675] Exctracting with p7zip to /tmp/it.mijorus.gearlever/appimages/gearlever_2r546da67p/squashfs-root
2024-12-28 16:00:07,713 DEBUG [terminal.py:42] Running ['7z', 'x', '/home/fab/appImagesClassic/BibleMultiTheLife-1.27.4-x86_64.AppImage', '-o/tmp/it.mijorus.gearlever/appimages/gearlever_2r546da67p/squashfs-root', '-y', '-bso0', 'bsp0', '*.png', '*.svg', '*.desktop', '.DirIcon', '-r']
2024-12-28 16:00:07,780 DEBUG [terminal.py:59] Done ['7z', 'x', '/home/fab/appImagesClassic/BibleMultiTheLife-1.27.4-x86_64.AppImage', '-o/tmp/it.mijorus.gearlever/appimages/gearlever_2r546da67p/squashfs-root', '-y', '-bso0', 'bsp0', '*.png', '*.svg', '*.desktop', '.DirIcon', '-r']
2024-12-28 16:00:07,780 DEBUG [AppImageProvider.py:680] 


2024-12-28 16:00:07,781 DEBUG [utils.py:74] Copying /tmp/it.mijorus.gearlever/appimages/gearlever_2r546da67p/squashfs-root/org.biblemulti.thelife.desktop to /tmp/it.mijorus.gearlever/appimages/gearlever_appimage_ac3cb14f0f9ad8d320ec79f098d25804/app.desktop
2024-12-28 16:00:07,782 DEBUG [AppImageProvider.py:752] Looking for icon in: /tmp/it.mijorus.gearlever/appimages/gearlever_2r546da67p/squashfs-root/usr/share/icons/hicolor/scalable/apps/org.biblemulti.thelife.svg
2024-12-28 16:00:07,782 DEBUG [AppImageProvider.py:752] Looking for icon in: /tmp/it.mijorus.gearlever/appimages/gearlever_2r546da67p/squashfs-root/usr/share/icons/hicolor/512x512/apps/org.biblemulti.thelife.png
2024-12-28 16:00:07,782 DEBUG [AppImageProvider.py:752] Looking for icon in: /tmp/it.mijorus.gearlever/appimages/gearlever_2r546da67p/squashfs-root/usr/share/icons/hicolor/256x256/apps/org.biblemulti.thelife.png
2024-12-28 16:00:07,783 DEBUG [AppImageProvider.py:752] Looking for icon in: /tmp/it.mijorus.gearlever/appimages/gearlever_2r546da67p/squashfs-root/usr/share/icons/hicolor/128x128/apps/org.biblemulti.thelife.png
2024-12-28 16:00:07,783 DEBUG [utils.py:74] Copying /tmp/it.mijorus.gearlever/appimages/gearlever_2r546da67p/squashfs-root/usr/share/icons/hicolor/128x128/apps/org.biblemulti.thelife.png to /tmp/it.mijorus.gearlever/appimages/gearlever_appimage_ac3cb14f0f9ad8d320ec79f098d25804/icon.png
2024-12-28 16:00:08,346 DEBUG [terminal.py:42] Running ['arch']
2024-12-28 16:00:08,349 DEBUG [terminal.py:59] Done ['arch']
2024-12-28 16:00:19,568 DEBUG [AppImageProvider.py:64] Chmod file /home/fab/appImagesClassic/BibleMultiTheLife-1.27.4-x86_64.AppImage
=> 2024-12-28 16:00:19,568 ERROR [AppDetails.py:340] [Errno 1] Operation not permitted: '/home/fab/appImagesClassic/BibleMultiTheLife-1.27.4-x86_64.AppImage'
2024-12-28 16:00:25,021 DEBUG [AppImageProvider.py:145] /home/fab/.local/share/applications/userapp-nano-TLCHZ2.desktop skipped because  does not exists on the filesystem
2024-12-28 16:00:25,021 DEBUG [terminal.py:42] Running ['file', '--brief', '--exclude-quiet=apptype', '--exclude-quiet=ascii', '--exclude-quiet=compress', '--exclude-quiet=csv', '--exclude-quiet=elf', '--exclude-quiet=encoding', '--exclude-quiet=tar', '--exclude-quiet=cdf', '--exclude-quiet=json', '--exclude-quiet=simh', '--exclude-quiet=text', '--exclude-quiet=tokens', '/home/fab/appImagesGearLever/notepad_next.appimage']
2024-12-28 16:00:25,032 DEBUG [terminal.py:59] Done ['file', '--brief', '--exclude-quiet=apptype', '--exclude-quiet=ascii', '--exclude-quiet=compress', '--exclude-quiet=csv', '--exclude-quiet=elf', '--exclude-quiet=encoding', '--exclude-quiet=tar', '--exclude-quiet=cdf', '--exclude-quiet=json', '--exclude-quiet=simh', '--exclude-quiet=text', '--exclude-quiet=tokens', '/home/fab/appImagesGearLever/notepad_next.appimage']
2024-12-28 16:00:25,033 DEBUG [AppImageProvider.py:145] /home/fab/.local/share/applications/userapp-nano-3TNXW2.desktop skipped because  does not exists on the filesystem
2024-12-28 16:00:25,033 DEBUG [AppImageProvider.py:145] /home/fab/.local/share/applications/biblemultithelife.desktop skipped because /home/fab/appImagesGearLever/biblemultithelife.appimage does not exists on the filesystem
```

**Comment by DIGist** [comment]
So I asked the Cromite team just in case. It appears they use "uruntime" instead of the normal appimage type 2 runtime. They wonder if the unzipping program doesn't work with dwarFS used in the uruntime:

https://github.com/pkgforge-dev/Cromite-AppImage/issues/10

**Comment by rporter220** [comment]
I'm seeing this behavior also with the new Goverlay appimage: [Goverlay 1.3 Portable Edition](https://github.com/benjamimgois/goverlay/releases)

Running Gear Lever from the CLI gives me ```Can not open the file as archive```
and the following:
```
Traceback (most recent call last):
  File "/app/bin/gearlever", line 44, in <module>
    sys.exit(main.main(VERSION, pkgdatadir))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/main.py", line 173, in main
    Cli.from_options(sys.argv)
  File "/app/share/gearlever/gearlever/Cli.py", line 42, in from_options
    getattr(Cli, name)(argv)
  File "/app/share/gearlever/gearlever/Cli.py", line 126, in integrate
    appimage_provider.refresh_title(el)
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 196, in refresh_title
    extracted = self._load_appimage_metadata(el)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 702, in _load_appimage_metadata
    mounted_appimage_path = self._extract_appimage(el)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 677, in _extract_appimage
    z7zoutput = '\n\n' + terminal.sandbox_sh(['7z', 'x', file.get_path(), f'-o{squashfs_root_folder}', '-y', '-bso0', 'bsp0', 
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/lib/terminal.py", line 52, in sandbox_sh
    raise e
  File "/app/share/gearlever/gearlever/lib/terminal.py", line 44, in sandbox_sh
    output.check_returncode()
  File "/usr/lib/python3.12/subprocess.py", line 504, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['7z', 'x', '/home/*******/Downloads/Goverlay_1_3.AppImage', '-o/tmp/it.mijorus.gearlever/appimages/gearlever_carcqy4yd9/squashfs-root', '-y', '-bso0', 'bsp0', '*.png', '*.svg', '*.desktop', '.DirIcon', '-r']' returned non-zero exit status 2.
```
